language: python

os:
    - linux

python:
    - 3.5
    - "3.5-dev"
    - 3.6
    - "3.6-dev"
    - 3.7
    - "3.7-dev"
    - "nightly"

install: pip install --progress-bar --user -r requirements.txt

script: make dev && make tests
