language: python

os:
    - linux
    - osx

python:
    - 3.5
    - 3.6
    - 3.7
    - "3.5-dev"
    - "3.6-dev"
    - "3.7-dev"

install: pip install -U pip && pip install --progress-bar off -r requirements.txt

script: make tests
