docs_dir: _build/pydocmd
nav:
- {Home: index.md}
- Tutorials:
  - {Distributed Policy Gradients with A2C: source/tutorials/distributed_a2c.md}
  - {Continuous Control with PPO: source/tutorials/continuous_ppo.md}
  - {Debugging Reinforcement Learning: source/tutorials/continuous_ppo.md}
- Documentation:
  - {cherry: docs/cherry.md}
  - {cherry.algorithms: docs/cherry.algorithms.md}
  - {cherry.envs: docs/cherry.envs.md}
  - {cherry.optim: docs/cherry.optim.md}
  - {cherry.rewards: docs/cherry.rewards.md}
  - {cherry.distributions: docs/cherry.distributions.md}
  - {cherry.utils: docs/cherry.utils.md}
  - {cherry.ExperienceReplay: docs/cherry.experience-replay.md}
site_dir: _build/site
site_name: Cherry
theme: {custom_dir: cherry_theme/, logo: docs/assets/img/cherry.png, name: flatly}
